[package]
name = "filecoin-proofs-ffi"
description = "FFI Interface to filecoin-proofs"
version = "0.1.0"
authors = ["laser <l@s3r.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/filecoin-project/rust-fil-proofs-ffi"
readme = "README.md"
edition = "2018"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
filecoin-proofs = "0.2.0"
ffi-toolkit = "0.2.0"
