[package]
name = "filecoin-ffi-shared"
version = "0.1.0"
authors = ["laser <l@s3r.com>"]
license = "MIT OR Apache-2.0"
description = "Shared Rust code for the Filecoin project"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
filecoin-proofs-ffi = { git = "https://github.com/filecoin-project/rust-fil-proofs-ffi.git", branch = "master" }

[build-dependencies]
cbindgen = "0.9"
